// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteToken() {
  return window['go']['main']['App']['DeleteToken']();
}

export function GetToken() {
  return window['go']['main']['App']['GetToken']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SaveToken(arg1) {
  return window['go']['main']['App']['SaveToken'](arg1);
}
