// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteToken():Promise<void>;

export function GetToken():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function SaveToken(arg1:string):Promise<void>;
